spring:
  profiles:
    include: secret
    active: prod
  servlet:  # S3 이미지 업로드 제한
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
  server:
    servlet:
      encoding:
        force-response: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/google
          github:
            clientId: ${GIT_CLIENT_ID}
            clientSecret: ${GIT_CLIENT_SECRET}
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/github
          kakao:
            clientId: ${K_CLIENT_ID}
            clientSecret: ${K_CLIENT_SECRET}
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/kakao
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: 7200000
  refresh-token-expire-time: 604800000
cloud:
  aws:
    s3:
      bucket: main20-pathfinder
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
open-api:
  tour-api:
    credentials:
      service-key: ${TOURAPI_SERVICEKEY}
backend:
  base-url: ec2-43-202-120-133.ap-northeast-2.compute.amazonaws.com:8080

frontend:
  base-url: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com

---

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope: email
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/google
          github:
            scope: user:email, read:user
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/github
          kakao:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
            redirect-uri: http://seb45-main-020.s3-website.ap-northeast-2.amazonaws.com/oauth2/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
